export const TAGS = [
  'Takedowns',
  'Guard Attacks',
  'Side-Control Attacks',
  'Mount Attacks',
  'Turtle Attacks',
  'Guard Sweeps',
  'Guard Passes',
  'Side-Control Escapes',
  'Back Escapes',
  'Mount Escapes',
  'Turtle Defenses',
  'Back Control',
  'Chokes',
  'Locks',
  'North-South',
  'X-Guard',
  'Rear-Naked Chokes',
  'Kimura',
  'Americana',
  'Knee on Belly',
  'Grips',
];
